CREATE TABLE IF NOT EXISTS posts (
    id bigserial PRIMARY KEY,
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    title text NOT NULL,
    author text NOT NULL,
    link text NOT NULL,
    subreddit_id bigint REFERENCES posts,
    content text NOT NULL,
    score integer NOT NULL DEFAULT 0,
    promoted bool NOT NULL DEFAULT FALSE,
    nsfw bool NOT NULL DEFAULT FALSE,
    version integer NOT NULL DEFAULT 1
);

INSERT INTO posts (title, author, link, content, score, promoted, nsfw)
VALUES
    ('This is the letter my neighbor sent me after I let him babysit my pets while I was on vacation.',
     't2_6qn61wcg', 'https://old.reddit.com/user/SnooCupcakes8607', 'Was at a lame business conference, but one of the speakers made a decent point',
     179000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_0qa4fk1g', 'https://old.reddit.com/user/nexte0lllkitevel',
     'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
     14400, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qqa6c31g', 'https://old.reddit.com/user/nexteddfrtinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qqa61gc3', 'https://old.reddit.com/user/khfrkhjsfgkhj',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    5000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qqa36c1g', 'https://old.reddit.com/user/agfggffg',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    154000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qc3qa61g', 'https://old.reddit.com/user/gagfgfgfga',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    24000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q3qa6c1g', 'https://old.reddit.com/user/agfgafgafg',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    4000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qq31ga6c', 'https://old.reddit.com/user/ngbfvgrt',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    5300, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qqa1g6c3', 'https://old.reddit.com/user/t5gfedc',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    4020, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qq1a6c3g', 'https://old.reddit.com/user/4efdcfgh5r',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54020, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q3q6c1ag', 'https://old.reddit.com/user/4rfrgtfeds',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    14000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_c31qa6gq', 'https://old.reddit.com/user/43rfg54fe',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    51000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qa6qc31g', 'https://old.reddit.com/user/4gfrvgh54fe',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    53000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qca631qg', 'https://old.reddit.com/user/4rfg4fegr4',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54400, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qc3aq61g', 'https://old.reddit.com/user/fg45frh65g',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54020, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qa6gc31q', 'https://old.reddit.com/user/4grh6jyhtgrfhj',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    24005, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q1qa63gc', 'https://old.reddit.com/user/9ijngredx',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    14000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_cqqa631g', 'https://old.reddit.com/user/p98uygvcdrtyuinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    53000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_cqqa631g', 'https://old.reddit.com/user/p98uygvcdrtyuinglevel',
     'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
     53000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_c3qqa61g', 'https://old.reddit.com/user/ldlvjlkd',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    14300, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_3a6cg1qq', 'https://old.reddit.com/user/nextndjvkkvl',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54200, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_3a1gqq6c', 'https://old.reddit.com/user/kdkkddfrtinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54001, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qvdfc31g', 'https://old.reddit.com/user/nepok49ojrtinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54006, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q2agrb1g', 'https://old.reddit.com/user/ne0okjmnj5vel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    64000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qp5k31g3', 'https://old.reddit.com/user/nexkvodllvel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    59000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q0a3of05', 'https://old.reddit.com/user/nekocvovkvel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    64003, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qqa36c1g', 'https://old.reddit.com/user/agfggffg',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    154000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qc3qa61g', 'https://old.reddit.com/user/gagfgfgfga',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    24000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q3qa6c1g', 'https://old.reddit.com/user/agfgafgafg',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    4000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qq31ga6c', 'https://old.reddit.com/user/ngbfvgrt',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    5300, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qqa1g6c3', 'https://old.reddit.com/user/t5gfedc',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    4020, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qq1a6c3g', 'https://old.reddit.com/user/4efdcfgh5r',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54020, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q3q6c1ag', 'https://old.reddit.com/user/4rfrgtfeds',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    14000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_c31qa6gq', 'https://old.reddit.com/user/43rfg54fe',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    51000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qa6qc31g', 'https://old.reddit.com/user/4gfrvgh54fe',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    53000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qca631qg', 'https://old.reddit.com/user/4rfg4fegr4',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54400, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qc3aq61g', 'https://old.reddit.com/user/fg45frh65g',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54020, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qa6gc31q', 'https://old.reddit.com/user/4grh6jyhtgrfhj',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
     24005, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q1qa63gc', 'https://old.reddit.com/user/9ijngredx',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    14000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_cqqa631g', 'https://old.reddit.com/user/p98uygvcdrtyuinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    53000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_c3qqa61g', 'https://old.reddit.com/user/ldlvjlkd',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    14300, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_1qqa6c3g', 'https://old.reddit.com/user/nexteddfrtinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54100, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_3a6cg1qq', 'https://old.reddit.com/user/nextndjvkkvl',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54200, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_3a1gqq6c', 'https://old.reddit.com/user/kdkkddfrtinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54001, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qvdfc31g', 'https://old.reddit.com/user/nepok49ojrtinglevel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    54006, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q2agrb1g', 'https://old.reddit.com/user/ne0okjmnj5vel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    64000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_qp5k31g3', 'https://old.reddit.com/user/nexkvodllvel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    59000, false, false),
    ('The precision needed here to activate a lighter with a tire', 't2_q0a3of05', 'https://old.reddit.com/user/nekocvovkvel',
    'He asked the crowd to raise their hands if they enjoyed helping their colleagues at work, even without recognition',
    64003, false, false);