name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

  tests:
    name: runner / tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Unit Tests
        run: "go test \
            -v \
            -race \
            -covermode atomic \
            -coverprofile=coverage.txt \
            ./internal/..."
      - name: End To End Tests
        run: "go test \
            -v \
            -race \
            -covermode atomic \
            -coverprofile=coverage.txt \
            ./cmd/api/..."
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)

      - name: Integration tests
        run: "docker-compose up \
            --build \
            --abort-on-container-exit \
            --exit-code-from integration"